# name the portage image
FROM gentoo/portage:latest as portage

# based on stage3 image
# FROM gentoo/stage3:amd64-hardened-20200905
FROM gentoo/stage3:latest

# copy the entire portage volume in
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

RUN emerge --noreplace dev-vcs/git
# COPY .gentoo /asmacdo/.gentoo
#
# RUN /asmacdo/.gentoo/install.sh
