# Pinned commits for the dependency tree state
ARG gentoo_hash=0f6aa0646baad09881e581250e24a4e018e14abc
ARG science_hash=a3ee59439b944fb12f7398f587ed6aac601fb96d

# name the portage image
FROM gentoo/portage:latest as portage

# based on stage3 image
# FROM gentoo/stage3:amd64-hardened-20200905
FROM gentoo/stage3:latest

# copy the entire portage volume in
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

RUN emerge --noreplace dev-vcs/git
RUN emerge --noreplace sys-apps/portage

COPY . /opfvta

RUN rsync -avP /opfvta/.gentoo/portage/ /etc/portage/
RUN rsync -avP /opfvta/.gentoo/overlay/ /var/db/repos/local_opfvta/

# Moving gentoo repo from default rsync to git
RUN rm /var/db/repos/gentoo -rf

# Getting everything via git
RUN emerge --sync science gentoo

# Pinning dependency tree state via git
# TODO control the history via dat
RUN pushd /var/db/repos/science; git fetch origin $science_hash; git checkout $science_hash; popd
RUN pushd /var/db/repos/gentoo; git fetch origin $gentoo_hash; git checkout $gentoo_hash; popd

# This is only if we distribute data separately
RUN echo "sci-biology/opfvta_bidsdata-2.0" > /etc/portage/profile/package.provided

RUN pushd /var/db/repos/local_opfvta/sci-misc/opfvta; ebuild opfvta-99999.ebuild manifest; popd
RUN FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox" emerge -v opfvta --autounmask-continue
